### PR TITLE
my-solution

### PR DESCRIPTION
**Pull request by JulienPascal**
Please execute the file "main.jl". It will go through the different questions and perform the tests listed in "test/tests.jl"

### CODE REVIEW

**Comment by JulianPasc** [comment]
It says "The Travis CI build failed", but the code passes all the tests on my computer.

**Comment by JulianPasc** [comment]
Any idea why Travis does not like my commit?

**Comment by floswald** [comment]
looks good, but i'm unable to run your code at all. I get 

```julia
julia> maxlike.runAll()
ERROR: MethodError: `dot` has no method matching dot(::Array{Float64,2}, ::Array{Float64,1})

You might have used a 2d row vector where a 1d column vector was required.
Note the difference between 1d column vector [1,2,3] and 2d row vector [1 2 3].
You can convert to a column vector with the vec() function.
Closest candidates are:
  dot(::AbstractArray{T,1}, ::AbstractArray{T,1})
 in plotLike at /Users/florian.oswald/Dropbox/teaching/ScPo/ScPo-CompEcon/HW_unconstrained/src/maxlike.jl:296
 in runAll at /Users/florian.oswald/Dropbox/teaching/ScPo/ScPo-CompEcon/HW_unconstrained/src/maxlike.jl:356
```

and 

```julia
julia> m1 = maxlike.maximize_like()
ERROR: UndefVarError: d not defined
 in loglik_for_optim at /Users/florian.oswald/Dropbox/teaching/ScPo/ScPo-CompEcon/HW_unconstrained/src/maxlike.jl:82
 in nelder_mead at /Users/florian.oswald/.julia/v0.4/Optim/src/nelder_mead.jl:74
 in optimize at /Users/florian.oswald/.julia/v0.4/Optim/src/optimize.jl:508
 in maximize_like at /Users/florian.oswald/Dropbox/teaching/ScPo/ScPo-CompEcon/HW_unconstrained/src/maxlike.jl:199
```

**Comment by JulianPasc** [comment]
Hi,

This is strange... I run the file "main.jl":
```
# Move to my folder: 
home = ENV["HOME"]
cd("/home/julien/HW-unconstrained")	

# include code: 
include("src/maxlike.jl")

# Load the maxLike module: 
using maxlike

# Run all the questions + the TESTS: 
maxlike.runAll() # Graph + optimization results + tests
```
Here is what I get:
screenshot from 2016-04-01 17 52 17

**Comment by floswald** [comment]
well then you probably changed the code after you pushed it, otherwise I can't explain that. do you want to push again?

**Comment by JulianPasc** [comment]
Yes I can push it again.

**Comment by JulianPasc** [comment]
Maybe I am doing something wrong, but when I want to push a new request using the Terminal, it tells me that "Everything is up-to-date". 
screenshot from 2016-04-01 18 04 12
I can try to add my files manually on the GitHub website if necessary.

**Comment by floswald** [comment]
don't do that - will figure something out instead.

**Comment by JulianPasc** [comment]
I have put my homework on a Google drive folder and shared it with you. Just in case there is a synchronization problem between my computer and GitHub.

**Comment by floswald** [comment]
I see in your code on google docs (which now we can safely assume is the same as the one on github)

```julia
➜  Google Drive cd HW_unconstrained 
➜  HW_unconstrained ls
Icon? src   test
➜  HW_unconstrained julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.3 (2016-01-12 21:37 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-apple-darwin13.4.0

julia> include("src/maxlike.jl")
maxlike

julia> maxlike.runAll()
ERROR: MethodError: `dot` has no method matching dot(::Array{Float64,2}, ::Array{Float64,1})

You might have used a 2d row vector where a 1d column vector was required.
Note the difference between 1d column vector [1,2,3] and 2d row vector [1 2 3].
You can convert to a column vector with the vec() function.
Closest candidates are:
  dot(::AbstractArray{T,1}, ::AbstractArray{T,1})
 in plotLike at /Users/florian.oswald/Google Drive/HW_unconstrained/src/maxlike.jl:296
 in runAll at /Users/florian.oswald/Google Drive/HW_unconstrained/src/maxlike.jl:356
```

and also all the tests error out with the same thing

```
julia> include("test/runtests.jl")
  > basics
Test Data Construction
1 fact verified.
Test Return value of likelihood
    Error :: (line:505) :: basics
      Expression: isempty(maxlike.loglik(d["beta"],d)) --> false
      MethodError: `dot` has no method matching dot(::Array{Float64,2}, ::Array{Float64,1})
      
      You might have used a 2d row vector where a 1d column vector was required.
      Note the difference between 1d column vector [1,2,3] and 2d row vector [1 2 3].
      You can convert to a column vector with the vec() function.
      Closest candidates are:
        dot(::AbstractArray{T,1}, ::AbstractArray{T,1})
       in loglik at /Users/florian.oswald/Google Drive/HW_unconstrained/src/maxlike.jl:70
       in anonymous at /Users/florian.oswald/.julia/v0.4/FactCheck/src/FactCheck.jl:271
       in do_fact at /Users/florian.oswald/.julia/v0.4/FactCheck/src/FactCheck.jl:333
       [inlined code] from /Users/florian.oswald/.julia/v0.4/FactCheck/src/FactCheck.jl:271
       in anonymous at /Users/florian.oswald/Google Drive/HW_unconstrained/test/tests.jl:14
       in facts at /Users/florian.oswald/.julia/v0.4/FactCheck/src/FactCheck.jl:448
       in anonymous at /Users/florian.oswald/Google Drive/HW_unconstrained/test/tests.jl:13
       in context at /Users/florian.oswald/.julia/v0.4/FactCheck/src/FactCheck.jl:474
       in include at /Applications/Julia-0.4.3.app/Contents/Resources/julia/lib/julia/sys.dylib
       in include_from_node1 at /Applications/Julia-0.4.3.app/Contents/Resources/julia/lib/julia/sys.dylib
       in include at /Applications/Julia-0.4.3.app/Contents/Resources/julia/lib/julia/sys.dylib
       in include_from_node1 at /Applications/Julia-0.4.3.app/Contents/Resources/julia/lib/julia/sys.dylib
Out of 1 total fact:
  Errored:  1
```

this is quite odd. what do you see when you do 

```
julia --version
```
?

**Comment by JulianPasc** [comment]
Yes, this is strange. I am running the version 0.5.0-dev
screenshot from 2016-04-01 21 50 56

**Comment by floswald** [comment]
well, then it's not so strange any more. i'll have to use the same version. i should have told you to use the latest stable version (i.e. 4.x.x), but not a big deal now - don't install anything else (unless you want to)

**Comment by floswald** [comment]
ok - runs. good job!

**Comment by JulianPasc** [comment]
Great. Thanks! Should I downgrade to the latest stable version for the next homeworks?

**Comment by floswald** [comment]
No, don't waste time on that. I would advise in general to use the latest
stable version. You may get caught in a bad place with packages who rely on
some new feature, which other packages don't support yet, etc.

**Pull request closed without merging**
